Allow unsetting and forcibly setting environment variables
viperML/wrapper-manager pull request #8
Opened 2023-09-30 10:34 UTC by nrabulinski

Closes #4.

On top of adding the ability to unset or forcibly set a value of a variable, I cleaned up the code a little and added shell argument escaping, so that every flag in `flags` actually gets treated as a separate argument and the end-user doesn't have to worry about using `escapeShellArg` or ensuring there's no illegal characters.

2023-09-30 11:21 UTC, viperML commented
Would there be any way to show a helpful message for the users of the old API ?

2023-09-30 12:08 UTC, nrabulinski commented
Honestly - not sure, I asked in the nix matrix if anyone has any idea. We could just as well add a new attribute instead of changing the type of the old one, but that'd come with even more friction and I don't think wrapper-manager is at a stage where you care that much about breakage 😄

2023-10-01 07:26 UTC, viperML requested changes

2023-10-01 07:32 UTC, nrabulinski commented on modules/env-type.nix
> +        nullOr strLike;
Because otherwise if I set default to null it won't type check, and I wanted a nice warning message if anyone set a value for an unset variable. Could be just as well achieved with an empty string though but there may be some instances where somebody wants to set a string to an empty value maybe? Not sure, it's your call.

2023-10-01 07:36 UTC, viperML commented on modules/env-type.nix
> +        nullOr strLike;
I feel there is some overlap of the same functionality, because `.force = true;` would always imply `.value = null;`.

Perhaps using `value = null;` should unset the var? But that would imply `.force = true` (unsetting without forcing doesn't make sense), so pick your poison.

```
FOO.unset = true;

vs

FOO.value = null;
```

🤔

2023-10-01 07:38 UTC, nrabulinski commented on modules/env-type.nix
> +        nullOr strLike;
Oh, that's actually a nice idea

2023-10-01 07:38 UTC, viperML commented on modules/env-type.nix
> +        nullOr strLike;
Aslo removing the default would force the user to actually choose a value explicitely.

2023-10-05 19:22 UTC, viperML commented
Thanks a lot! Documentation seems to be OK too

2023-10-05 19:22 UTC, merged